### ISSUE TITLE
Pasar valores absolutos a valores relativos para facilitar el responsive

### ISSUE THREAD

**Issue by telemaca** [telemaca/proyectoFinal#25]
@solzapata @julia-sartirana Les propongo que a partir de ahora usemos siempre que podamos la medida `vw` (view width) en lugares de pixeles para facilitar el responsive. Yo me adjudico este issue para lo que ya está hecho, pero para que lo tengan en cuenta en lo que hagamos a partir de ahora. (La medida la estoy usando todo el tiempo en el trabajo y es una maravilla lo que facilita todo)

**Comment by julia-sartirana** [comment]
dale! genial
