### ISSUE TITLE
Instalar react-bootstrap

### ISSUE THREAD

**Issue by telemaca** [telemaca/proyectoFinal#60]
Ayer lo único que llegué a hacer fue instalar esto jaja. Pero en principio lo usaríamos para el modal del video y si podemos, un carousel de cards. si quieren ir ganando tiempo, pueden ir instalándolo así eventualmente no les tira error:
yarn add react-bootstrap bootstrap

**Comment by julia-sartirana** [comment]
Jajaja dale, ya lo instalo! Y vamos con ese carousel 💪🏼
