### ISSUE TITLE
Crear página de Error

### ISSUE THREAD

**Issue by julia-sartirana** [telemaca/proyectoFinal#61]

**Comment by telemaca** [comment]
Tenía pensado maquetar eso con algo de Star Wars, tipo "This is not the page you are looking for" y un Obi-Wan con animaciiones :D :D :D

**Comment by julia-sartirana** [comment]
Ay, les iba a decir lo mismo 😍 poner algo de fondo de star wars ya que lo tenemos en el loading también. Me encanta!

**Comment by telemaca** [comment]
Ya qué me robé descaradamente el BB-8, también podemos usar este AT-AT: 
https://codepen.io/r4ms3s/pen/gajVBG
Igual sigo buscando a ver si hay más copados
@julia-sartirana  @solzapata

**Comment by julia-sartirana** [comment]
Jaja totalmente! me encanta ese 😍 Voy a chusmear también pero es re ese el estilo
