### ISSUE TITLE
Si tenemos ganas y tiempo, podemos hacer que dé la opción de ver en inglés o español

### ISSUE THREAD

**Issue by telemaca** [telemaca/proyectoFinal#63]

**Comment by julia-sartirana** [comment]
Siii! Lo voy a ir repasando un poquito 😊

**Comment by telemaca** [comment]
Creo que con un ENUM en cada archivo (o un archivo de ENUMs, e importamos cada uno dnd corresponda), se puede hacer de manera super simple. Un estado general (en un contexto que sea LanguageContext) dnd se defina el idioma, y según el elegido, un ternario determina qué va. No es complicado, solo lleva un poco de tiempo je
