### ISSUE TITLE
¿Deberíamos agregar botón/ícono de "atrás"?

### ISSUE THREAD

**Issue by telemaca** [telemaca/proyectoFinal#65]
El de Home no porque está siempre visible, pero creo que deberíamos agregar el de ir para atrás con useHistory

**Comment by julia-sartirana** [comment]
si, se re puede agregar con el Go de useHistory. Tambien podriamos poner otro fijo para scroll hacia arriba no?

**Comment by telemaca** [comment]
ahhhh buenísimo eso del scroll, sí! :D
